### ISSUE TITLE
Definitely this example must be done in TCP/UDP

### ISSUE THREAD

**Issue by rianby64** [rianby64/arca-ws-examples#2]
Turn out the transport ```WS``` into  ```TCP/UDP```.

**Comment by rianby64** [comment]
The CAD system is going to send the information via TCP from C#. I've no choice.

**Comment by szhilkin** [comment]
Lets use "proxy" that will be listening on TCP port and translate requests to WebSocket.

**Comment by rianby64** [comment]
Found a solution via socket.io
